import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

export type SupportedLang = 'es' | 'en';

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private languageSubject = new BehaviorSubject<SupportedLang>(this.loadLanguage());
  public language$ = this.languageSubject.asObservable();

  private translations: Record<string, Record<SupportedLang, string>>;

  constructor() {
    const appTitle = this.loadAppTitle() ?? 'BDIC Admin Panel';
    this.translations = {
      // Navigation
      'app.title': { es: appTitle, en: appTitle },
      'nav.dashboard': { es: 'Dashboard', en: 'Dashboard' },
      'nav.moderation': { es: 'Feed de Moderación', en: 'Moderation Feed' },
      'nav.appeals': { es: 'Apelaciones', en: 'Appeals' },
      'nav.reports': { es: 'Reportes', en: 'Reports' },
      'nav.reviews': { es: 'Reseñas', en: 'Reviews' },
      'nav.announcements': { es: 'Anuncios', en: 'Announcements' },
      'nav.places': { es: 'Lugares', en: 'Places' },
      'nav.categories': { es: 'Categorías', en: 'Categories' },
      'nav.users': { es: 'Usuarios', en: 'Users' },
      'nav.verifications': { es: 'Verificaciones', en: 'Verifications' },
      'nav.badges': { es: 'Insignias', en: 'Badges' },
      'nav.settings': { es: 'Configuración', en: 'Settings' },
      'nav.system': { es: 'Sistema', en: 'System' },
      'nav.logout': { es: 'Cerrar sesión', en: 'Logout' },

      // Places
      'places.title': { es: 'Gestión de Lugares', en: 'Places Management' },
      'places.add': { es: 'Agregar Lugar', en: 'Add Place' },
      'places.refresh': { es: 'Actualizar', en: 'Refresh' },
      'places.search': { es: 'Buscar por nombre...', en: 'Search by name...' },
      'places.category': { es: 'Categoría', en: 'Category' },
      'places.status': { es: 'Estado', en: 'Status' },
      'places.all': { es: 'Todos', en: 'All' },
      'places.name': { es: 'Nombre', en: 'Name' },
      'places.category_label': { es: 'Categoría', en: 'Category' },
      'places.images': { es: 'Imágenes', en: 'Images' },
      'places.rating': { es: 'Calificación', en: 'Rating' },
      'places.verified_label': { es: 'Verificado', en: 'Verified' },
      'places.verified': { es: 'Verificado', en: 'Verified' },
      'places.unverified': { es: 'No Verificado', en: 'Unverified' },
      'places.created': { es: 'Creado', en: 'Created' },
      'places.actions': { es: 'Acciones', en: 'Actions' },
      'places.edit': { es: 'Editar', en: 'Edit' },
      'places.images_manage': { es: 'Gestionar Imágenes', en: 'Manage Images' },
      'places.loading': { es: 'Cargando lugares...', en: 'Loading places...' },
      'places.verified_success': { es: 'Lugar verificado exitosamente', en: 'Place verified successfully' },
      'places.deleted_success': { es: 'Lugar eliminado exitosamente', en: 'Place deleted successfully' },
      'places.delete_confirm': { es: '¿Estás seguro de que deseas eliminar', en: 'Are you sure you want to delete' },
      'places.error': { es: 'Error al procesar el lugar', en: 'Error processing place' },
      'places.restaurant': { es: 'Restaurante', en: 'Restaurant' },
      'places.cafe': { es: 'Café', en: 'Café' },
      'places.bar': { es: 'Bar', en: 'Bar' },
      'places.hotel': { es: 'Hotel', en: 'Hotel' },
      'places.attraction': { es: 'Atracción', en: 'Attraction' },
      'places.other': { es: 'Otro', en: 'Other' },
      'places.security': { es: 'Seguridad', en: 'Security' },
      'places.cinema': { es: 'Cine', en: 'Cinema' },
      'places.taxi_station': { es: 'Estación de Taxis', en: 'Taxi Station' },
      'places.bus_station': { es: 'Estación de Buses', en: 'Bus Station' },
      'places.point_of_interest': { es: 'Punto de Interés', en: 'Point of Interest' },
      'places.museum': { es: 'Museo', en: 'Museum' },
      'places.library': { es: 'Biblioteca', en: 'Library' },
      'places.gym': { es: 'Gimnasio', en: 'Gym' },
      'places.hospital': { es: 'Hospital', en: 'Hospital' },
      'places.pharmacy': { es: 'Farmacia', en: 'Pharmacy' },
      'places.bank': { es: 'Banco', en: 'Bank' },
      'places.post_office': { es: 'Oficina de Correos', en: 'Post Office' },
      'places.supermarket': { es: 'Supermercado', en: 'Supermarket' },
      'places.shopping_mall': { es: 'Centro Comercial', en: 'Shopping Mall' },
      'places.amusement_park': { es: 'Parque de Diversiones', en: 'Amusement Park' },
      'places.verify': { es: 'Verificar', en: 'Verify' },
      'places.delete': { es: 'Eliminar', en: 'Delete' },
      'places.department': { es: 'Departamento', en: 'Department' },
      'places.city': { es: 'Ciudad', en: 'City' },
      'places.sector': { es: 'Sector', en: 'Sector' },
      'places.photo_status': { es: 'Estado de Foto', en: 'Photo Status' },
      'places.clear_filters': { es: 'Limpiar Filtros', en: 'Clear Filters' },

      // Appeals
      'appeals.title': { es: 'Apelaciones', en: 'Appeals' },
      'appeals.no_found': { es: 'No hay apelaciones', en: 'No appeals found' },
      'appeals.pending': { es: 'Pendiente', en: 'Pending' },
      'appeals.approved': { es: 'Aprobada', en: 'Approved' },
      'appeals.rejected': { es: 'Rechazada', en: 'Rejected' },
      'appeals.reason': { es: 'Razón', en: 'Reason' },
      'appeals.user': { es: 'Usuario', en: 'User' },
      'appeals.date': { es: 'Fecha', en: 'Date' },
      'appeals.actions': { es: 'Acciones', en: 'Actions' },
      'appeals.approve': { es: 'Aprobar', en: 'Approve' },
      'appeals.reject': { es: 'Rechazar', en: 'Reject' },

      // Moderation Feed
      'moderation.title': { es: 'Feed de Moderación', en: 'Moderation Feed' },
      'moderation.refresh': { es: 'Actualizar', en: 'Refresh' },
      'moderation.search': { es: 'Buscar por usuario...', en: 'Search by user...' },
      'moderation.type': { es: 'Tipo', en: 'Type' },
      'moderation.status': { es: 'Estado', en: 'Status' },
      'moderation.automoderated': { es: 'Automoderado', en: 'Auto-moderated' },
      'moderation.all': { es: 'Todos', en: 'All' },
      'moderation.pending': { es: 'Pendiente', en: 'Pending' },
      'moderation.approved': { es: 'Aprobado', en: 'Approved' },
      'moderation.deleted': { es: 'Eliminado', en: 'Deleted' },
      'moderation.user_banned': { es: 'Usuario baneado', en: 'User Banned' },
      'moderation.yes': { es: 'Sí', en: 'Yes' },
      'moderation.no': { es: 'No', en: 'No' },
      'moderation.id': { es: 'ID', en: 'ID' },
      'moderation.type_label': { es: 'Tipo', en: 'Type' },
      'moderation.user': { es: 'Usuario', en: 'User' },
      'moderation.reason': { es: 'Razón', en: 'Reason' },
      'moderation.action': { es: 'Acción', en: 'Action' },
      'moderation.date': { es: 'Fecha', en: 'Date' },
      'moderation.actions': { es: 'Acciones', en: 'Actions' },
      'moderation.view_detail': { es: 'Ver detalle', en: 'View Detail' },
      'moderation.verify': { es: 'Verificar', en: 'Verify' },
      'moderation.reject': { es: 'Rechazar', en: 'Reject' },
      'moderation.comment': { es: 'Comentario', en: 'Comment' },
      'moderation.review': { es: 'Reseña', en: 'Review' },
      'moderation.place': { es: 'Lugar', en: 'Place' },
      'moderation.photo': { es: 'Foto', en: 'Photo' },
      'moderation.total_reports': { es: 'Total de Reportes', en: 'Total Reports' },

      // Announcements
      'announcements.title': { es: 'Anuncios', en: 'Announcements' },
      'announcements.info_banner': { es: 'Crear, editar y gestionar anuncios que aparecerán en el mapa. Establece duración y ubicación.', en: 'Create, edit and manage announcements that will appear on the map. Set duration and location.' },
      'announcements.total': { es: 'Total de Anuncios', en: 'Total Announcements' },
      'announcements.create': { es: 'Crear Anuncio', en: 'Create Announcement' },
      'announcements.edit': { es: 'Editar Anuncio', en: 'Edit Announcement' },
      'announcements.delete': { es: 'Eliminar Anuncio', en: 'Delete Announcement' },
      'announcements.title_label': { es: 'Título', en: 'Title' },
      'announcements.message': { es: 'Mensaje', en: 'Message' },
      'announcements.description': { es: 'Descripción', en: 'Description' },
      'announcements.type': { es: 'Tipo', en: 'Type' },
      'announcements.type_promotion': { es: 'Promoción', en: 'Promotion' },
      'announcements.type_event': { es: 'Evento', en: 'Event' },
      'announcements.type_alert': { es: 'Alerta', en: 'Alert' },
      'announcements.type_general': { es: 'General', en: 'General' },
      'announcements.duration': { es: 'Duración', en: 'Duration' },
      'announcements.start_date': { es: 'Fecha de Inicio', en: 'Start Date' },
      'announcements.end_date': { es: 'Fecha de Fin', en: 'End Date' },
      'announcements.location': { es: 'Ubicación', en: 'Location' },
      'announcements.address': { es: 'Dirección', en: 'Address' },
      'announcements.latitude': { es: 'Latitud', en: 'Latitude' },
      'announcements.longitude': { es: 'Longitud', en: 'Longitude' },
      'announcements.image_url': { es: 'URL de Imagen', en: 'Image URL' },
      'announcements.external_link': { es: 'Enlace Externo', en: 'External Link' },
      'announcements.pinned': { es: 'Anclado', en: 'Pinned' },
      'announcements.status': { es: 'Estado', en: 'Status' },
      'announcements.status_active': { es: 'Activo', en: 'Active' },
      'announcements.status_expired': { es: 'Expirado', en: 'Expired' },
      'announcements.status_draft': { es: 'Borrador', en: 'Draft' },
      'announcements.status_archived': { es: 'Archivado', en: 'Archived' },
      'announcements.created_by': { es: 'Creado por', en: 'Created by' },
      'announcements.views': { es: 'Vistas', en: 'Views' },
      'announcements.clicks': { es: 'Clics', en: 'Clicks' },
      'announcements.created_success': { es: 'Anuncio creado exitosamente', en: 'Announcement created successfully' },
      'announcements.updated_success': { es: 'Anuncio actualizado exitosamente', en: 'Announcement updated successfully' },
      'announcements.deleted_success': { es: 'Anuncio eliminado exitosamente', en: 'Announcement deleted successfully' },
      'announcements.pinned_success': { es: 'Anuncio anclado exitosamente', en: 'Announcement pinned successfully' },
      'announcements.unpinned_success': { es: 'Anuncio desanclado exitosamente', en: 'Announcement unpinned successfully' },
      'announcements.loading': { es: 'Cargando anuncios...', en: 'Loading announcements...' },
      
      // Report Reasons
      'reason.spam': { es: 'Spam', en: 'Spam' },
      'reason.harassment': { es: 'Acoso', en: 'Harassment' },
      'reason.hate_speech': { es: 'Discurso de odio', en: 'Hate Speech' },
      'reason.violence': { es: 'Violencia', en: 'Violence' },
      'reason.sexual_content': { es: 'Contenido sexual', en: 'Sexual Content' },
      'reason.false_info': { es: 'Información falsa', en: 'False Information' },
      'reason.copyright': { es: 'Derechos de autor', en: 'Copyright' },
      'reason.other': { es: 'Otro', en: 'Other' },

      // Moderation Detail
      'moderation_detail.title': { es: 'Detalle del Reporte', en: 'Report Detail' },
      'moderation_detail.back': { es: 'Volver', en: 'Back' },
      'moderation_detail.report_info': { es: 'Información del Reporte', en: 'Report Information' },
      'moderation_detail.type': { es: 'Tipo', en: 'Type' },
      'moderation_detail.reason': { es: 'Razón', en: 'Reason' },
      'moderation_detail.status': { es: 'Estado', en: 'Status' },
      'moderation_detail.date': { es: 'Fecha', en: 'Date' },
      'moderation_detail.reporter_info': { es: 'Información del Reportador', en: 'Reporter Information' },
      'moderation_detail.reported_user_info': { es: 'Información del Usuario Reportado', en: 'Reported User Information' },
      'moderation_detail.content': { es: 'Contenido', en: 'Content' },
      'moderation_detail.actions': { es: 'Acciones de Moderación', en: 'Moderation Actions' },
      'moderation_detail.verify': { es: 'Verificar', en: 'Verify' },
      'moderation_detail.reject': { es: 'Rechazar', en: 'Reject' },
      'moderation_detail.mute': { es: 'Silenciar 24h', en: 'Mute 24h' },
      'moderation_detail.ban': { es: 'Banear', en: 'Ban' },
      'moderation_detail.note': { es: 'Nota privada', en: 'Private Note' },

      // Reports
      'reports.title': { es: 'Reportes', en: 'Reports' },
      'reports.total': { es: 'Total de Reportes', en: 'Total Reports' },
      'reports.pending': { es: 'Pendientes', en: 'Pending' },
      'reports.approved': { es: 'Aprobados', en: 'Approved' },
      'reports.rejected': { es: 'Rechazados', en: 'Rejected' },
      'reports.by_type': { es: 'Reportes por Tipo', en: 'Reports by Type' },
      'reports.by_reason': { es: 'Reportes por Razón', en: 'Reports by Reason' },
      'reports.top_reported_places': { es: 'Lugares Reportados (Top 5)', en: 'Top Reported Places (Top 5)' },
      'reports.top_reported_users': { es: 'Usuarios Reportados (Top 5)', en: 'Top Reported Users (Top 5)' },
      'reports.top_reported': { es: 'Usuarios Más Reportados', en: 'Top Reported Users' },
      'reports.top_10_reported': { es: 'Top 10 Usuarios Más Reportados', en: 'Top 10 Reported Users' },
      'reports.top_reporting_users': { es: 'Usuarios que Más Reportan', en: 'Top Reporting Users' },
      'reports.top_10_reporting_users': { es: 'Top 10 Usuarios que Más Reportan', en: 'Top 10 Reporting Users' },
      'reports.count_label': { es: 'reportes', en: 'reports' },
      'reports.export': { es: 'Exportar', en: 'Export' },
      'reports.export_csv': { es: 'Exportar CSV', en: 'Export CSV' },
      'reports.export_excel': { es: 'Exportar Excel', en: 'Export Excel' },
      'reports.export_pdf': { es: 'Exportar PDF', en: 'Export PDF' },
      'reports.until': { es: 'Hasta', en: 'Until' },
      'reports.apply_filters': { es: 'Aplicar Filtros', en: 'Apply Filters' },
      'reports.loading': { es: 'Cargando reportes...', en: 'Loading reports...' },
      'reports.how_it_works': { es: '¿Cómo funciona el sistema de moderación?', en: 'How does the moderation system work?' },
      'reports.statistics': { es: 'Estadísticas:', en: 'Statistics:' },
      'reports.statistics_desc': { es: 'Visualiza el estado general de todos los reportes. Cada métrica muestra el progreso y distribución de acciones.', en: 'View the overall status of all reports. Each metric shows the progress and distribution of actions.' },
      'reports.auto_moderation': { es: 'Auto-Moderación:', en: 'Auto-Moderation:' },
      'reports.auto_moderation_desc': { es: 'El sistema detecta automáticamente contenido problemático. Los reportes auto-moderados se procesan sin intervención manual.', en: 'The system automatically detects problematic content. Auto-moderated reports are processed without manual intervention.' },
      'reports.advanced_filters': { es: 'Filtros Avanzados:', en: 'Advanced Filters:' },
      'reports.advanced_filters_desc': { es: 'Filtra por estado, tipo de contenido, moderación automática o manual, y busca reportes específicos.', en: 'Filter by status, content type, automatic or manual moderation, and search for specific reports.' },
      'reports.data_export': { es: 'Exportación de Datos:', en: 'Data Export:' },
      'reports.data_export_desc': { es: 'Descarga todos los registros filtrados en formato CSV para análisis externo o reportes.', en: 'Download all filtered records in CSV format for external analysis or reports.' },
      'reports.auto_moderated': { es: 'Auto-Moderados', en: 'Auto-Moderated' },
      'reports.manually_moderated': { es: 'Moderados Manualmente', en: 'Manually Moderated' },
      'reports.hidden': { es: 'Ocultos', en: 'Hidden' },
      'reports.banned_users': { es: 'Usuarios Baneados', en: 'Banned Users' },
      'reports.auto_moderation_criteria': { es: 'Criterios de Auto-Moderación:', en: 'Auto-Moderation Criteria:' },
      'reports.criteria_toxicity': { es: 'Toxicidad detectada (análisis de sentimiento)', en: 'Toxicity detected (sentiment analysis)' },
      'reports.criteria_spam': { es: 'Spam o contenido duplicado', en: 'Spam or duplicate content' },
      'reports.criteria_keywords': { es: 'Palabras clave prohibidas', en: 'Prohibited keywords' },
      'reports.criteria_patterns': { es: 'Patrones de abuso conocidos', en: 'Known abuse patterns' },
      'reports.criteria_multiple': { es: 'Reportes múltiples del mismo contenido', en: 'Multiple reports of the same content' },
      'reports.filter_reports': { es: 'Filtrar Reportes', en: 'Filter Reports' },
      'reports.report_type': { es: 'Tipo de Reporte', en: 'Report Type' },
      'reports.type_comment': { es: 'Comentario', en: 'Comment' },
      'reports.type_review': { es: 'Reseña / Valoración', en: 'Review / Rating' },
      'reports.type_place': { es: 'Lugar', en: 'Place' },
      'reports.status_pending': { es: 'Pendiente', en: 'Pending' },
      'reports.status_approved': { es: 'Aprobado', en: 'Approved' },
      'reports.status_rejected': { es: 'Rechazado', en: 'Rejected' },
      'reports.moderation_type': { es: 'Tipo de Moderación', en: 'Moderation Type' },
      'reports.severity': { es: 'Severidad', en: 'Severity' },
      'reports.severity_low': { es: 'Baja', en: 'Low' },
      'reports.severity_medium': { es: 'Media', en: 'Medium' },
      'reports.severity_high': { es: 'Alta', en: 'High' },
      'reports.from_date': { es: 'Desde', en: 'From Date' },
      'reports.all_reports': { es: 'Todos los Reportes', en: 'All Reports' },
      'reports.reports_list': { es: 'Listado de Reportes', en: 'Reports List' },
      'reports.type': { es: 'Tipo', en: 'Type' },
      'reports.reason': { es: 'Razón', en: 'Reason' },

      // User Profile
      'user_profile.loading': { es: 'Cargando perfil...', en: 'Loading profile...' },
      'user_profile.username': { es: 'Usuario:', en: 'Username:' },
      'user_profile.internal_id': { es: 'ID interno:', en: 'Internal ID:' },
      'user_profile.email': { es: 'Email:', en: 'Email:' },
      'user_profile.role': { es: 'Rol:', en: 'Role:' },
      'user_profile.status': { es: 'Estado:', en: 'Status:' },
      'user_profile.ban_reason': { es: 'Razón del baneo:', en: 'Ban Reason:' },
      'user_profile.not_specified': { es: 'No especificada', en: 'Not specified' },
      'user_profile.muted_until': { es: 'Silenciado hasta:', en: 'Muted Until:' },
      'user_profile.created': { es: 'Creado:', en: 'Created:' },
      'user_profile.updated': { es: 'Actualizado:', en: 'Updated:' },
      'user_profile.bio': { es: 'Biografía:', en: 'Biography:' },
      'user_profile.location': { es: 'Ubicación:', en: 'Location:' },
      'user_profile.places': { es: 'Lugares', en: 'Places' },
      'user_profile.reviews': { es: 'Reseñas', en: 'Reviews' },
      'user_profile.rating': { es: 'Calificación', en: 'Rating' },
      'user_profile.reports': { es: 'Reportes', en: 'Reports' },
      'user_profile.back': { es: '← Volver', en: '← Back' },
      'user_profile.edit': { es: '✏️ Editar Usuario', en: '✏️ Edit User' },
      'user_profile.error': { es: 'No se pudo cargar el perfil del usuario.', en: 'Could not load user profile.' },
      'user_profile.banned': { es: 'Baneado', en: 'Banned' },
      'user_profile.muted': { es: 'Silenciado', en: 'Muted' },
      'user_profile.active': { es: 'Activo', en: 'Active' },

      // Users
      'users.title': { es: 'Gestión de Usuarios', en: 'User Management' },
      'users.add': { es: 'Agregar Usuario', en: 'Add User' },
      'users.refresh': { es: 'Actualizar', en: 'Refresh' },
      'users.search': { es: 'Buscar por nombre...', en: 'Search by name...' },
      'users.role': { es: 'Rol', en: 'Role' },
      'users.status': { es: 'Estado', en: 'Status' },
      'users.all': { es: 'Todos', en: 'All' },
      'users.username': { es: 'Usuario', en: 'Username' },
      'users.email': { es: 'Correo', en: 'Email' },
      'users.role_label': { es: 'Rol', en: 'Role' },
      'users.reputation': { es: 'Reputación', en: 'Reputation' },
      'users.actions': { es: 'Acciones', en: 'Actions' },
      'users.view_profile': { es: 'Ver Perfil', en: 'View Profile' },
      'users.edit': { es: 'Editar', en: 'Edit' },
      'users.manage_badges': { es: 'Gestionar Insignias', en: 'Manage Badges' },
      'users.mute': { es: 'Silenciar', en: 'Mute' },
      'users.ban': { es: 'Banear', en: 'Ban' },
      'users.loading': { es: 'Cargando usuarios...', en: 'Loading users...' },
      'users.banned': { es: 'Baneado', en: 'Banned' },
      'users.muted': { es: 'Silenciado', en: 'Muted' },
      'users.no_data': { es: 'No hay usuarios registrados.', en: 'No users registered.' },
      'users.error_id': { es: 'Error: No se pudo obtener el ID del usuario', en: 'Error: Could not get user ID' },
      'users.mute_hours': { es: '¿Cuántas horas deseas silenciar al usuario?', en: 'How many hours do you want to mute the user?' },
      'users.muted_success': { es: 'Usuario silenciado por', en: 'User muted for' },
      'users.hours': { es: 'horas', en: 'hours' },
      'users.mute_error': { es: 'Error al silenciar el usuario', en: 'Error muting user' },
      'users.ban_reason': { es: '¿Cuál es la razón del baneo?', en: 'What is the reason for the ban?' },
      'users.ban_success': { es: 'Usuario baneado exitosamente. Razón:', en: 'User banned successfully. Reason:' },
      'users.ban_error': { es: 'Error al banear el usuario', en: 'Error banning user' },
      'users.reset_confirm': { es: '¿Enviar email de reset de contraseña a', en: 'Send password reset email to' },
      'users.reset_sent': { es: 'Email de reset enviado a', en: 'Reset email sent to' },
      'users.reset_error': { es: 'Error al enviar email de reset', en: 'Error sending reset email' },
      'users.delete_confirm': { es: '¿Estás seguro de que deseas eliminar a', en: 'Are you sure you want to delete' },
      'users.delete_warning': { es: 'Esta acción no se puede deshacer.', en: 'This action cannot be undone.' },
      'users.delete_success': { es: 'Usuario eliminado exitosamente', en: 'User deleted successfully' },
      'users.delete_error': { es: 'Error al eliminar el usuario', en: 'Error deleting user' },

      // Settings
      'settings.title': { es: 'Configuración', en: 'Settings' },
      'settings.subtitle': { es: 'Gestiona la configuración del panel administrativo', en: 'Manage admin panel settings' },
      'settings.general': { es: 'Configuración General', en: 'General Settings' },
      'settings.app_name': { es: 'Nombre de la Aplicación', en: 'Application Name' },
      'settings.support_email': { es: 'Email de Soporte', en: 'Support Email' },
      'settings.support_phone': { es: 'Teléfono de Soporte', en: 'Support Phone' },
      'settings.website_url': { es: 'URL del Sitio Web', en: 'Website URL' },
      'settings.theme': { es: 'Tema y Apariencia', en: 'Theme & Appearance' },
      'settings.default_theme': { es: 'Tema por Defecto', en: 'Default Theme' },
      'settings.light': { es: 'Claro', en: 'Light' },
      'settings.dark': { es: 'Oscuro', en: 'Dark' },
      'settings.auto': { es: 'Automático', en: 'Auto' },
      'settings.enable_animations': { es: 'Habilitar Animaciones', en: 'Enable Animations' },
      'settings.compact_mode': { es: 'Modo Compacto', en: 'Compact Mode' },
      'settings.primary_color': { es: 'Color Primario', en: 'Primary Color' },
      'settings.security': { es: 'Seguridad', en: 'Security' },
      'settings.session_timeout': { es: 'Tiempo de Sesión (minutos)', en: 'Session Timeout (minutes)' },
      'settings.two_factor': { es: 'Requerir Autenticación de Dos Factores', en: 'Require Two-Factor Authentication' },
      'settings.ip_whitelist': { es: 'Habilitar Lista Blanca de IPs', en: 'Enable IP Whitelist' },
      'settings.audit_log': { es: 'Habilitar Registro de Auditoría', en: 'Enable Audit Log' },
      'settings.moderation': { es: 'Moderación', en: 'Moderation' },
      'settings.default_mute_hours': { es: 'Tiempo de Silenciamiento por Defecto (horas)', en: 'Default Mute Duration (hours)' },
      'settings.autoban_threshold': { es: 'Umbral de Reportes para Baneo Automático', en: 'Auto-ban Report Threshold' },
      'settings.enable_automod': { es: 'Habilitar Moderación Automática', en: 'Enable Auto Moderation' },
      'settings.notify_reports': { es: 'Notificar sobre Nuevos Reportes', en: 'Notify on New Reports' },
      'settings.email': { es: 'Configuración de Email', en: 'Email Settings' },
      'settings.smtp_server': { es: 'Servidor SMTP', en: 'SMTP Server' },
      'settings.smtp_port': { es: 'Puerto SMTP', en: 'SMTP Port' },
      'settings.sender_email': { es: 'Email del Remitente', en: 'Sender Email' },
      'settings.enable_email_notif': { es: 'Habilitar Notificaciones por Email', en: 'Enable Email Notifications' },
      'settings.api': { es: 'Configuración de API', en: 'API Settings' },
      'settings.api_url': { es: 'URL del Backend', en: 'Backend URL' },
      'settings.api_timeout': { es: 'Timeout de API (segundos)', en: 'API Timeout (seconds)' },
      'settings.enable_api_logging': { es: 'Habilitar Registro de API', en: 'Enable API Logging' },
      'settings.enable_caching': { es: 'Habilitar Caché', en: 'Enable Caching' },
      'settings.backup': { es: 'Copias de Seguridad', en: 'Backups' },
      'settings.backup_frequency': { es: 'Frecuencia de Copias de Seguridad', en: 'Backup Frequency' },
      'settings.daily': { es: 'Diaria', en: 'Daily' },
      'settings.weekly': { es: 'Semanal', en: 'Weekly' },
      'settings.monthly': { es: 'Mensual', en: 'Monthly' },
      'settings.backup_retention': { es: 'Retención de Copias (días)', en: 'Backup Retention (days)' },
      'settings.auto_backup': { es: 'Copias de Seguridad Automáticas', en: 'Auto Backups' },
      'settings.create_backup': { es: 'Crear Copia Ahora', en: 'Create Backup Now' },
      'settings.reset': { es: 'Restaurar Valores por Defecto', en: 'Reset to Defaults' },
      'settings.save': { es: 'Guardar Cambios', en: 'Save Changes' },
      'settings.saved_success': { es: '✓ Configuración guardada exitosamente', en: '✓ Settings saved successfully' },
      'settings.save_error': { es: 'Error al guardar la configuración', en: 'Error saving settings' },
      'settings.reset_confirm': { es: '¿Estás seguro de que deseas restaurar los valores por defecto?', en: 'Are you sure you want to reset to default values?' },
      'settings.backup_success': { es: '✓ Copia de seguridad creada exitosamente', en: '✓ Backup created successfully' },

      // Verifications
      'verifications.title': { es: 'Solicitudes de Verificación', en: 'Verification Requests' },
      'verifications.info_banner': { es: 'Revisa y gestiona solicitudes de verificación de usuarios. Aprueba o rechaza solicitudes después de revisar la evidencia.', en: 'Review and manage user verification requests. Approve or reject requests after reviewing the evidence.' },
      'verifications.total': { es: 'Total de Solicitudes', en: 'Total Requests' },
      'verifications.refresh': { es: 'Actualizar', en: 'Refresh' },
      'verifications.search': { es: 'Buscar por usuario...', en: 'Search by user...' },
      'verifications.status': { es: 'Estado', en: 'Status' },
      'verifications.all': { es: 'Todos', en: 'All' },
      'verifications.pending': { es: 'Pendiente', en: 'Pending' },
      'verifications.approved': { es: 'Aprobado', en: 'Approved' },
      'verifications.rejected': { es: 'Rechazado', en: 'Rejected' },
      'verifications.name': { es: 'Nombre', en: 'Name' },
      'verifications.username': { es: 'Usuario', en: 'Username' },
      'verifications.email': { es: 'Correo', en: 'Email' },
      'verifications.status_label': { es: 'Estado', en: 'Status' },
      'verifications.date': { es: 'Fecha Solicitud', en: 'Request Date' },
      'verifications.actions': { es: 'Acciones', en: 'Actions' },
      'verifications.view_detail': { es: 'Ver Evidencia', en: 'View Evidence' },
      'verifications.approve': { es: 'Aprobar', en: 'Approve' },
      'verifications.reject': { es: 'Rechazar', en: 'Reject' },
      'verifications.loading': { es: 'Cargando solicitudes...', en: 'Loading requests...' },

      // Badges
      'badges.title': { es: 'Gestión de Insignias', en: 'Badges Management' },
      'badges.add': { es: 'Agregar Insignia', en: 'Add Badge' },
      'badges.refresh': { es: 'Actualizar', en: 'Refresh' },
      'badges.search': { es: 'Buscar por nombre...', en: 'Search by name...' },
      'badges.name': { es: 'Nombre', en: 'Name' },
      'badges.description': { es: 'Descripción', en: 'Description' },
      'badges.actions': { es: 'Acciones', en: 'Actions' },
      'badges.edit': { es: 'Editar', en: 'Edit' },
      'badges.delete': { es: 'Eliminar', en: 'Delete' },
      'badges.loading': { es: 'Cargando insignias...', en: 'Loading badges...' },

      // Advanced Moderation Dashboard
      'moderation.dashboard_title': { es: 'Panel de Moderación Automática', en: 'Automated Moderation Dashboard' },
      'moderation.dashboard_subtitle': { es: 'Sistema robusto de moderación con detección automática y sanciones progresivas', en: 'Robust moderation system with automatic detection and progressive sanctions' },
      'moderation.statistics': { es: 'Estadísticas', en: 'Statistics' },
      'moderation.moderation_logs': { es: 'Logs de Moderación', en: 'Moderation Logs' },
      'moderation.system_info': { es: 'Información del Sistema', en: 'System Information' },
      'moderation.total_actions': { es: 'Acciones Totales', en: 'Total Actions' },
      'moderation.affected_users': { es: 'Usuarios Afectados', en: 'Affected Users' },
      'moderation.avg_toxicity': { es: 'Toxicidad Promedio', en: 'Average Toxicity' },
      'moderation.avg_spam': { es: 'Spam Promedio', en: 'Average Spam' },
      'moderation.actions_by_type': { es: 'Acciones por Tipo', en: 'Actions by Type' },
      'moderation.severity_distribution': { es: 'Distribución de Severidad', en: 'Severity Distribution' },
      'moderation.top_reasons': { es: 'Razones Principales', en: 'Top Reasons' },
      'moderation.period': { es: 'Período', en: 'Period' },
      'moderation.last_7_days': { es: 'Últimos 7 días', en: 'Last 7 days' },
      'moderation.last_30_days': { es: 'Últimos 30 días', en: 'Last 30 days' },
      'moderation.last_90_days': { es: 'Últimos 90 días', en: 'Last 90 days' },
      'moderation.action_type': { es: 'Tipo de Acción', en: 'Action Type' },
      'moderation.comment_hidden': { es: 'Comentario Oculto', en: 'Comment Hidden' },
      'moderation.comment_deleted': { es: 'Comentario Eliminado', en: 'Comment Deleted' },
      'moderation.user_muted': { es: 'Usuario Silenciado', en: 'User Muted' },
      'moderation.content_flagged': { es: 'Contenido Marcado', en: 'Content Flagged' },
      'moderation.search_user_or_content': { es: 'Buscar usuario o contenido...', en: 'Search user or content...' },
      'moderation.total_records': { es: 'Total de Registros', en: 'Total Records' },
      'moderation.detected_issues': { es: 'Problemas Detectados', en: 'Detected Issues' },
      'moderation.more_actions': { es: 'Más Acciones', en: 'More Actions' },
      'moderation.view_violations': { es: 'Ver Violaciones', en: 'View Violations' },
      'moderation.view_profile': { es: 'Ver Perfil', en: 'View Profile' },
      'moderation.view_details': { es: 'Ver Detalles', en: 'View Details' },
      'moderation.export': { es: 'Exportar', en: 'Export' },
      'moderation.how_system_works': { es: '¿Cómo funciona el sistema?', en: 'How does the system work?' },
      'moderation.automated_detection': { es: 'Detección Automática', en: 'Automated Detection' },
      'moderation.automated_detection_desc': { es: 'El sistema analiza automáticamente todo el contenido publicado para detectar violaciones de políticas de comunidad.', en: 'The system automatically analyzes all published content to detect community policy violations.' },
      'moderation.bad_words_detection': { es: 'Detección de malas palabras (3 niveles de severidad)', en: 'Bad words detection (3 severity levels)' },
      'moderation.spam_detection': { es: 'Detección de spam (caracteres repetidos, URLs, teléfonos)', en: 'Spam detection (repeated chars, URLs, phones)' },
      'moderation.toxicity_analysis': { es: 'Análisis de toxicidad con IA', en: 'AI-powered toxicity analysis' },
      'moderation.trust_score_calc': { es: 'Cálculo de puntuación de confianza del usuario', en: 'User trust score calculation' },
      'moderation.progressive_sanctions': { es: 'Sanciones Progresivas', en: 'Progressive Sanctions' },
      'moderation.progressive_sanctions_desc': { es: 'Las sanciones aumentan según el historial de violaciones del usuario, respetando usuarios de confianza.', en: 'Sanctions increase based on user violation history, respecting trusted users.' },
      'moderation.violation': { es: 'violación', en: 'violation' },
      'moderation.violations': { es: 'violaciones', en: 'violations' },
      'moderation.severe_violations': { es: 'violaciones severas', en: 'severe violations' },
      'moderation.flag_for_review': { es: 'Marcar para revisión', en: 'Flag for review' },
      'moderation.mute_24h': { es: 'Silencio 24 horas', en: 'Mute 24 hours' },
      'moderation.mute_3days': { es: 'Silencio 3 días', en: 'Mute 3 days' },
      'moderation.mute_7days': { es: 'Silencio 7 días', en: 'Mute 7 days' },
      'moderation.permanent_mute': { es: 'Silencio permanente', en: 'Permanent mute' },
      'moderation.permanent_ban': { es: 'Ban permanente', en: 'Permanent ban' },
      'moderation.severity_levels': { es: 'Niveles de Severidad', en: 'Severity Levels' },
      'moderation.mild_desc': { es: 'Contenido con lenguaje inapropiado leve. Marcado para revisión.', en: 'Content with mild inappropriate language. Flagged for review.' },
      'moderation.moderate_desc': { es: 'Contenido con lenguaje ofensivo moderado. Oculto automáticamente.', en: 'Content with moderate offensive language. Automatically hidden.' },
      'moderation.severe_desc': { es: 'Contenido con lenguaje severo o amenazas. Eliminado y usuario sancionado.', en: 'Content with severe language or threats. Deleted and user sanctioned.' },
      'moderation.select_page': { es: 'Seleccionar página de registros', en: 'Select page of records' },

      // Common
      'common.yes': { es: 'Sí', en: 'Yes' },
      'common.no': { es: 'No', en: 'No' },
      'common.loading': { es: 'Cargando...', en: 'Loading...' },
      'common.error': { es: 'Error', en: 'Error' },
      'common.success': { es: 'Éxito', en: 'Success' },
      'common.cancel': { es: 'Cancelar', en: 'Cancel' },
      'common.save': { es: 'Guardar', en: 'Save' },
      'common.delete': { es: 'Eliminar', en: 'Delete' },
      'common.edit': { es: 'Editar', en: 'Edit' },
      'common.add': { es: 'Agregar', en: 'Add' },
      'common.filter': { es: 'Filtros Avanzados', en: 'Advanced Filters' },
      'common.more': { es: 'Más', en: 'More' },
      'common.refresh': { es: 'Actualizar', en: 'Refresh' },
      'common.actions': { es: 'Acciones', en: 'Actions' },
      'common.search': { es: 'Buscar', en: 'Search' },
      'common.days': { es: 'días', en: 'days' },
      'common.hours': { es: 'horas', en: 'hours' },
      'common.confirm': { es: 'Confirmar', en: 'Confirm' },
      'common.close': { es: 'Cerrar', en: 'Close' },
      'common.name': { es: 'Nombre', en: 'Name' },
      'common.created': { es: 'Creado', en: 'Created' },
      'common.user': { es: 'Usuario', en: 'User' },
      'common.date': { es: 'Fecha', en: 'Date' },
      'common.status': { es: 'Estado', en: 'Status' },
      'common.all': { es: 'Todos', en: 'All' },
      'common.verified': { es: 'Verificado', en: 'Verified' },
      'common.unverified': { es: 'No Verificado', en: 'Unverified' },

      // Dashboard
      'dashboard.title': { es: 'Dashboard', en: 'Dashboard' },
      'dashboard.export': { es: 'Exportar Datos', en: 'Export Data' },
      'dashboard.total_users': { es: 'Usuarios Totales', en: 'Total Users' },
      'dashboard.total_places': { es: 'Lugares Registrados', en: 'Registered Places' },
      'dashboard.total_reports': { es: 'Reportes', en: 'Reports' },
      'dashboard.total_ratings': { es: 'Valoraciones', en: 'Ratings' },
      'dashboard.users_by_role': { es: 'Distribución de Usuarios por Rol', en: 'Users Distribution by Role' },
      'dashboard.places_by_category': { es: 'Lugares por Categoría', en: 'Places by Category' },
      'dashboard.reports_by_type': { es: 'Reportes por Tipo', en: 'Reports by Type' },
      'dashboard.activity_7days': { es: 'Actividad Últimos 7 Días', en: 'Activity Last 7 Days' },
      'dashboard.demographics': { es: 'Datos Demográficos', en: 'Demographics' },
      'dashboard.user_locations': { es: 'Ubicación de Usuarios', en: 'User Locations' },
      'dashboard.top_places': { es: 'Lugares Más Visitados', en: 'Top Places' },
      'dashboard.popular_categories': { es: 'Categorías Populares', en: 'Popular Categories' },
      'dashboard.report_stats': { es: 'Estadísticas de Reportes', en: 'Report Statistics' },
      'dashboard.resolved': { es: 'Resueltos', en: 'Resolved' },
      'dashboard.pending': { es: 'Pendientes', en: 'Pending' },
      'dashboard.resolution_rate': { es: 'Tasa de Resolución', en: 'Resolution Rate' },
      'dashboard.visits': { es: 'visitas', en: 'visits' },
      'dashboard.recent_activity': { es: 'Actividad Reciente', en: 'Recent Activity' },
      'dashboard.most_reported_content': { es: 'Contenido Más Reportado', en: 'Most Reported Content' },
      'dashboard.top_reporters': { es: 'Usuarios Más Reportadores', en: 'Top Reporters' },
      'dashboard.system_health': { es: 'Salud del Sistema', en: 'System Health' },
      'dashboard.database': { es: 'Base de Datos', en: 'Database' },
      'dashboard.api': { es: 'API', en: 'API' },
      'dashboard.notifications': { es: 'Notificaciones', en: 'Notifications' },
      'dashboard.storage': { es: 'Almacenamiento', en: 'Storage' },
      'dashboard.healthy': { es: 'Saludable', en: 'Healthy' },
      'dashboard.uptime': { es: 'Tiempo de Actividad', en: 'Uptime' },
      'dashboard.latency': { es: 'Latencia', en: 'Latency' },
      'dashboard.active': { es: 'Activo', en: 'Active' },
      'dashboard.usage': { es: 'Uso', en: 'Usage' },
      'dashboard.id': { es: 'ID', en: 'ID' },
      'dashboard.content': { es: 'Contenido', en: 'Content' },
      'dashboard.user': { es: 'Usuario', en: 'User' },
      'dashboard.date': { es: 'Fecha', en: 'Date' },
      'dashboard.status': { es: 'Estado', en: 'Status' },
      'dashboard.action': { es: 'Acción', en: 'Action' },
      'dashboard.moderator': { es: 'Moderador', en: 'Moderator' },
      'dashboard.reports': { es: 'reportes', en: 'reports' },
      'dashboard.accuracy': { es: 'Precisión', en: 'Accuracy' },
      'dashboard.close': { es: 'Cerrar', en: 'Close' },
      'dashboard.report_details': { es: 'Detalles del Reporte', en: 'Report Details' },
      'dashboard.reported_content': { es: 'Contenido Reportado', en: 'Reported Content' },
      'dashboard.place_content': { es: 'Lugar/Contenido', en: 'Place/Content' },
      'dashboard.type': { es: 'Tipo', en: 'Type' },
      'dashboard.reason': { es: 'Razón', en: 'Reason' },
      'dashboard.report_description': { es: 'Descripción del Reporte', en: 'Report Description' },
      'dashboard.reporter_info': { es: 'Información del Reportador', en: 'Reporter Information' },
      'dashboard.moderation_info': { es: 'Información de Moderación', en: 'Moderation Information' },
      'dashboard.moderated_by': { es: 'Moderado por', en: 'Moderated by' },
      'dashboard.moderation_date': { es: 'Fecha de Moderación', en: 'Moderation Date' },
      'dashboard.moderation_notes': { es: 'Notas', en: 'Notes' },
      'dashboard.content_image': { es: 'Imagen del Contenido', en: 'Content Image' },
      'dashboard.view_full_report': { es: 'Ver Reporte Completo', en: 'View Full Report' },
      'dashboard.reports_by_reason': { es: 'Reportes por Razón', en: 'Reports by Reason' },
      'dashboard.report_by_user': { es: 'Reporte por Usuario', en: 'Report by User' },
      
      // Common
      'common.unknown_user': { es: 'Usuario desconocido', en: 'Unknown User' },

      // Reports Dialog
      'reports.username_label': { es: 'Nombre / Username', en: 'Username' },
      'reports.email_label': { es: 'Email', en: 'Email' },
      'reports.action_label': { es: 'Acción sobre el contenido', en: 'Action on Content' },
      'reports.action_pending': { es: 'Pendiente', en: 'Pending' },
      'reports.action_approved': { es: 'Aprobado / Publicado', en: 'Approved / Published' },
      'reports.action_hidden': { es: 'Ocultar contenido', en: 'Hide Content' },
      'reports.action_deleted': { es: 'Borrar contenido', en: 'Delete Content' },
      'reports.action_banned': { es: 'Banear usuario', en: 'Ban User' },
      'reports.notes_label': { es: 'Notas internas para el equipo', en: 'Internal Notes' },
      'reports.notes_placeholder': { es: 'Agrega notas sobre la decisión tomada...', en: 'Add notes about the decision...' },
      'reports.current_status': { es: 'Estado actual', en: 'Current Status' },
      'reports.moderated_at': { es: 'el', en: 'on' },
      'reports.saving': { es: 'Guardando...', en: 'Saving...' },
      'reports.save_changes': { es: 'Guardar Cambios', en: 'Save Changes' },

      // Reviews
      'reviews.title': { es: 'Reseñas y Reportes', en: 'Reviews and Reports' },
      'reviews.info_banner': { es: 'Ver, verificar y gestionar reseñas de usuarios. Haz clic en una reseña para ver detalles o usa los botones de acción.', en: 'View, verify and manage user reviews. Click on a review to see details or use the action buttons.' },
      'reviews.total': { es: 'Total de Reseñas', en: 'Total Reviews' },
      'reviews.search_place': { es: 'Buscar por lugar...', en: 'Search by place...' },
      'reviews.filter_place': { es: 'Filtrar por lugar', en: 'Filter by place' },
      'reviews.filter_status': { es: 'Filtrar por estado', en: 'Filter by status' },
      'reviews.place': { es: 'Lugar', en: 'Place' },
      'reviews.user': { es: 'Usuario', en: 'User' },
      'reviews.rating': { es: 'Calificación', en: 'Rating' },
      'reviews.title_label': { es: 'Título', en: 'Title' },
      'reviews.content': { es: 'Contenido', en: 'Content' },
      'reviews.date': { es: 'Fecha', en: 'Date' },
      'reviews.status': { es: 'Estado', en: 'Status' },
      'reviews.verified': { es: 'Verificada', en: 'Verified' },
      'reviews.unverified': { es: 'No Verificada', en: 'Unverified' },
      'reviews.reported': { es: 'Reportada', en: 'Reported' },
      'reviews.view_detail': { es: 'Ver Detalle', en: 'View Detail' },
      'reviews.verify': { es: 'Verificar', en: 'Verify' },
      'reviews.verify_confirm': { es: '¿Verificar reseña', en: 'Verify review' },
      'reviews.verified_success': { es: 'Reseña verificada exitosamente', en: 'Review verified successfully' },
      'reviews.deleted_success': { es: 'Reseña eliminada exitosamente', en: 'Review deleted successfully' },
      'reviews.loading': { es: 'Cargando reseñas...', en: 'Loading reviews...' },

      // Categories (Map)
      'categories.title': { es: 'Categorías', en: 'Categories' },
      'categories.subtitle': { es: 'Administra las categorías de lugares en el sistema', en: 'Manage place categories in the system' },
      'categories.search': { es: 'Buscar categorías', en: 'Search categories' },
      'categories.search_placeholder': { es: 'Nombre de categoría', en: 'Category name' },
      'categories.all': { es: 'Todas', en: 'All' },
      'categories.active': { es: 'Activas', en: 'Active' },
      'categories.inactive': { es: 'Inactivas', en: 'Inactive' },
      'categories.add': { es: 'Nueva Categoría', en: 'New Category' },
      'categories.name': { es: 'Nombre', en: 'Name' },
      'categories.description': { es: 'Descripción', en: 'Description' },
      'categories.no_description': { es: 'Sin descripción', en: 'No description' },
      'categories.icon': { es: 'Icono', en: 'Icon' },
      'categories.color': { es: 'Color', en: 'Color' },
      'categories.places': { es: 'Lugares', en: 'Places' },
      'categories.status': { es: 'Estado', en: 'Status' },
      'categories.edit': { es: 'Editar categoría', en: 'Edit category' },
      'categories.toggle_status': { es: 'Cambiar estado', en: 'Toggle status' },
      'categories.delete': { es: 'Eliminar categoría', en: 'Delete category' },
      'categories.no_found': { es: 'No se encontraron categorías', en: 'No categories found' },
      'categories.empty_hint': { es: 'Intenta ajustar los filtros o crea una nueva categoría', en: 'Try adjusting the filters or create a new category' },
      'categories.security': { es: 'Seguridad', en: 'Security' },
      'categories.cinema': { es: 'Cine', en: 'Cinema' },
      'categories.taxi_station': { es: 'Estación de Taxis', en: 'Taxi Station' },
      'categories.bus_station': { es: 'Estación de Buses', en: 'Bus Station' },
      'categories.point_of_interest': { es: 'Punto de Interés', en: 'Point of Interest' },
      'categories.museum': { es: 'Museo', en: 'Museum' },
      'categories.library': { es: 'Biblioteca', en: 'Library' },
      'categories.gym': { es: 'Gimnasio', en: 'Gym' },
      'categories.hospital': { es: 'Hospital', en: 'Hospital' },
      'categories.pharmacy': { es: 'Farmacia', en: 'Pharmacy' },
      'categories.bank': { es: 'Banco', en: 'Bank' },
      'categories.post_office': { es: 'Oficina de Correos', en: 'Post Office' },
      'categories.supermarket': { es: 'Supermercado', en: 'Supermarket' },
      'categories.shopping_mall': { es: 'Centro Comercial', en: 'Shopping Mall' },
      'categories.amusement_park': { es: 'Parque de Diversiones', en: 'Amusement Park' },

      // Verification
      'verification.title': { es: 'Gestión de Verificación de Usuarios', en: 'User Verification Management' },
      'verification.subtitle': { es: 'Monitorea y gestiona la verificación de identidad de usuarios', en: 'Monitor and manage user identity verification' },
      'verification.total_users': { es: 'Total de Usuarios', en: 'Total Users' },
      'verification.verified_users': { es: 'Usuarios Verificados', en: 'Verified Users' },
      'verification.partially_verified': { es: 'Parcialmente Verificados', en: 'Partially Verified' },
      'verification.unverified_users': { es: 'Usuarios No Verificados', en: 'Unverified Users' },
      'verification.email_verified': { es: 'Email Verificado', en: 'Email Verified' },
      'verification.name_validated': { es: 'Nombre Validado', en: 'Name Validated' },
      'verification.filters': { es: 'Filtros', en: 'Filters' },
      'verification.filter_by_level': { es: 'Filtrar por nivel de verificación', en: 'Filter by verification level' },
      'verification.filter_by_email': { es: 'Filtrar por estado de email', en: 'Filter by email status' },
      'verification.filter_by_name': { es: 'Filtrar por validación de nombre', en: 'Filter by name validation' },
      'verification.all': { es: 'Todos', en: 'All' },
      'verification.verified': { es: 'Verificado', en: 'Verified' },
      'verification.not_verified': { es: 'No Verificado', en: 'Not Verified' },
      'verification.valid': { es: 'Válido', en: 'Valid' },
      'verification.invalid': { es: 'Inválido', en: 'Invalid' },
      'verification.pending': { es: 'Pendiente', en: 'Pending' },
      'verification.refresh': { es: 'Actualizar', en: 'Refresh' },
      'verification.users_list': { es: 'Lista de Usuarios', en: 'Users List' },
      'verification.name': { es: 'Nombre', en: 'Name' },
      'verification.username': { es: 'Usuario', en: 'Username' },
      'verification.email': { es: 'Email', en: 'Email' },
      'verification.email_status': { es: 'Estado Email', en: 'Email Status' },
      'verification.name_status': { es: 'Estado Nombre', en: 'Name Status' },
      'verification.level': { es: 'Nivel de Verificación', en: 'Verification Level' },
      'verification.actions': { es: 'Acciones', en: 'Actions' },
      'verification.view_details': { es: 'Ver detalles', en: 'View details' },
      'verification.manually_verify': { es: 'Verificar manualmente', en: 'Manually verify' },
      'verification.reject': { es: 'Rechazar', en: 'Reject' },
      'verification.no_users': { es: 'No hay usuarios para mostrar', en: 'No users to display' }
    };
  }

  private loadLanguage(): SupportedLang {
    const saved = localStorage.getItem('adminLang');
    if (saved === 'es' || saved === 'en') {
      return saved;
    }
    return 'es';
  }

  private loadAppTitle(): string | null {
    const saved = localStorage.getItem('adminSettings');
    if (!saved) {
      return null;
    }
    try {
      const settings = JSON.parse(saved);
      if (settings && typeof settings.appName === 'string' && settings.appName.trim().length > 0) {
        return settings.appName.trim();
      }
    } catch {
      return null;
    }
    return null;
  }

  setLanguage(lang: SupportedLang): void {
    this.languageSubject.next(lang);
    localStorage.setItem('adminLang', lang);
  }

  get currentLanguage(): SupportedLang {
    return this.languageSubject.value;
  }

  translate(key: string): string {
    const lang = this.languageSubject.value;
    const entry = this.translations[key];
    if (!entry) {
      return key;
    }
    return entry[lang] ?? entry['es'] ?? key;
  }
}
